export { AD_CONFIG, isAdDemoMode } from '../config/ads'
export { AdBanner } from './AdBanner'
export type { AdBannerProps } from './AdBanner'
export { AdInterstitial } from './AdInterstitial'
export type { AdInterstitialProps } from './AdInterstitial'
export { AdManagerProvider, useAdManager } from './AdManagerProvider'
export type { AdManagerProviderProps } from './AdManagerProvider'
export { loadAdScript, useAdManagerState } from './useAdManager'
export type { AdManagerState, AdPlacement } from './useAdManager'
